### ISSUE TITLE
Missing dependency ?

### ISSUE THREAD

**Issue by jeanremy** [mgibeau/semantic-release-expo-github-action#3]
Hi,

I'm using this GitHub Action, but it leads to an error: Cannot find module '@semantic-release/error'. I don't know if it comes from the action or my configuration. 
Here is my workflow file:
```
name: Handle expo build
on:
  push:
    branches: [next, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Expo Semantic Release
        uses: mgibeau/semantic-release-expo-github-action@v0.2-alpha
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    ...

```
Am I missing something ?

Thanks for your help.
